{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stonedb-helm.fullname" . }}-pvc
spec:
  accessModes: {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}