apiVersion: v1
kind: Service
metadata:
  name: {{ include "stonedb-helm.fullname" . }}-svc
  labels:
    {{- include "stonedb-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "stonedb-helm.selectorLabels" . | nindent 4 }}
