apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "stonedb-helm.fullname" . }}-sts
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stonedb-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stonedb-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stonedb-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- if ne .Values.image.pullSecret "" }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.nameOverride }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{.Values.env.password}}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/stonedb57/install/data
              name: data
            - mountPath: /opt/stonedb57/install/my.cnf
              name: config
              subPath: my.cnf
          livenessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 100
            periodSeconds: 20
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "stonedb-helm.fullname" . }}-pvc
        - name: config
          configMap:
            name: {{ include "stonedb-helm.fullname" . }}-cm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
